server:
  port: 3081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: Service1Module
        uri: http://localhost:3001/
        predicates:
        - Path=/Service1s/**
      - id: Service2Module
        uri: http://localhost:3002/
        predicates:
        - Path=/Service2s/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true