q2.

- Demonstrate the updation of image in live container in a pod using command line as well as by updating yaml files

apiVersion: apps/v1
kind: Deployment
metadata:
  name: usn-nginx-deployment
  labels:
    app: usn-nginx
spec:
  replicas: 3
  selector:
    matchLables:
      app: usn-nginx
  template:
    metadata:
      labels:
        app: usn-nginx
    spec:
      containers:
      - name: nginx
        image: 172.1.14.168:5001/nginx
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80

kubectl apply -f dep2.yaml
kubectl expose deployment usn-nginx-deployment --type=NodePort --name=usn-nginx-service

kubectl set image deployment/usn-nginx-deployment nginx=newImage

kubectl describe deploy usn-nginx-deployment | grep image
