q5->
apiVersion: v1
kind: Pod
metadata:
   name: ubuntu
   labels:
      app: ubuntu
spec:
   containers:
   - name: ubuntu
     image: 172.1.14.168:5001/ubuntu
     env:
     - name: MESSAGE
       value: "MSRIT"
     command: ["/bin/echo"]
     args: ["$(MESSAGE)"]

kubectl apply -f dep5.yaml
kubectl logs ubuntu
kubectl delete pod ubuntu
